### PR TITLE
fix(BModal): Allow prevent hide event.

### PR DESCRIPTION
**Pull request by bradlis7**
# Describe the PR

If I do `@ok.prevent`, I don't want it to hide the Modal.

## Small replication

N/A

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

### CODE REVIEW

**Comment by VividLemon** [comment]
This already works 
image

**Comment by bradlis7** [comment]
Hm, yes in this case, it does. But I want to have a hide callback that doesn't get called if prevented.

```
<BModal
  :model-value="componentState.show"
  @ok.prevent="onOkClick()"
  @hide="onHide"
>
```

I'm doing this for now.

```
  @ok.prevent="onOkClick"
  @close="onHide"
  @cancel="onHide"
```

I could check for $event.defaultPrevented in my own code, but I don't think it should trigger `@hide` at all if it's prevented earlier.

**Comment by VividLemon** [comment]
> Hm, yes in this case, it does. But I want to have a hide callback that doesn't get called if prevented.
> 
> ```
> <BModal
>   :model-value="componentState.show"
>   @ok.prevent="onOkClick()"
>   @hide="onHide"
> >
> ```
> 
> I'm doing this for now.
> 
> ```
>   @ok.prevent="onOkClick"
>   @hide.prevent
>   @close="onHide"
>   @cancel="onHide"
> ```
> 
> I could check for $event.defaultPrevented in my own code, but I don't think it should trigger `@hide` at all if it's prevented earlier.

This is Bootstrap-vue compatibility

image

It's just how it works in their system. 

You have two options. In our system, you have the `hide-prevented` emit. Which you can use to modify behavior. Alternatively, which is likely the better option, the event emitted also has access to `event.defaultPrevented`. You can check this on your side of the app and modify from there.

**Comment by bradlis7** [comment]
👍 I'll work around it.

**Pull request closed without merging**
