### PR TITLE
fix(BFormCheckbox): indeterminate state fixes #2271

### LINKED ISSUE #2271: Form Check Indeterminate state not visible
### Describe the bug

Hello,

The indeterminate state of the form check is not visible anymore (all browsers).

I bisected down to version [0.24.13](https://github.com/bootstrap-vue-next/bootstrap-vue-next/releases/tag/bootstrapvuenext-v0.24.13) which is first version where the indeterminate state is broken.

I suspect the addition of the `.attr` modifier to be the cause of the problem:

https://github.com/bootstrap-vue-next/bootstrap-vue-next/compare/bootstrapvuenext-v0.24.12...bootstrapvuenext-v0.24.13#diff-fe736d79412d0c67d64c9eb398a2089cacec94461d0f69f5376ad66caa9bcd3eR23

Thanks for all the all work on this project!

### Reproduction

https://stackblitz.com/edit/github-tzq5ew?file=src%2Fcomponents%2FComp.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by VividLemon**
# Describe the PR

A clear and concise description of what the pull request does.

## Small replication

A small replication or video walkthrough can help demonstrate the changes made. This is optional, but can help observe the intended changes. A mentioned issue that contains a replication also works.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [ ] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

### CODE REVIEW

**Comment by xvaara** [comment]
@VividLemon is there a reason why you'd like to remove the indeterminate prop from dom? You should fix the tests also if this was the intention.

**Comment by VividLemon** [comment]
> @VividLemon is there a reason why you'd like to remove the indeterminate prop from dom? You should fix the tests also if this was the intent.

It's not a dom attribute, it's a javascript psuedoclass

**Comment by xvaara** [comment]
TIL

**Comment by dwgray** [comment]
> > @VividLemon is there a reason why you'd like to remove the indeterminate prop from dom? You should fix the tests also if this was the intent.
> 
> It's not a dom attribute, it's a javascript psuedoclass

I feel like this is likely causing the test failure on #2276, but let me know if you think otherwise @VividLemon and I'll dig into it...

**Comment by xvaara** [comment]
> > > @VividLemon is there a reason why you'd like to remove the indeterminate prop from dom? You should fix the tests also if this was the intent.
> > 
> > 
> > It's not a dom attribute, it's a javascript psuedoclass
> 
> I feel like this is likely causing the test failure on #2276, but let me know if you think otherwise @VividLemon and I'll dig into it...

Yes it is, we need to fix the tests. Just remove the failing tests, they are wrong :) indeterminate prop should not be in dom as the test expexts.

**Pull request merged**
