### PR TITLE
Tmp

### PR DESCRIPTION
**Pull request by VividLemon**
# Describe the PR

A clear and concise description of what the pull request does.

## Small replication

If the change is large enough, a small replication can help demonstrate the changes made. This is optional, but can help observe the intended changes. A mentioned issue that contains a replication also works.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [ ] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

### CODE REVIEW

**Comment by StirStudios** [comment]
Seems I have caused a bit of grief, sorry about this!!

**Comment by VividLemon** [comment]
> Seems I have caused a bit of grief, sorry about this!!

@StirStudios 

I have squash merged everything. 

You may want to:

1. Keep your local changes intact, do not fetch upstream and merge
2. Delete your fork
3. "Refork" -- fork the project again
4. go to your command line on your repository and run `git pull origin main` (assuming remote "origin" and branch "main"
5. Check if there are any merge conflicts. Take note of any changes, do not attempt to fix them, simply note them

- If the changes are good -- as in the changes are not "missing" items, then everything should be fine, 
- if there is something missing or changed, take note of it. Do not attempt to fix the issue

6. Catalogue any issues
7. Delete your local repository
8. Git clone your fork
9. Fix the issues that you took note of
10. Make a new PR

Surely this process of deleting your fork, deleting your local repository, etc, etc is a bit unconventional, but it's likely the best way to preserve a linear history, and not have to deal with the merge conflicts. However, if you're a "git guru" you can likely do it whatever way you want to sync your repository, and make sure there isn't anything missing.

**Comment by VividLemon** [comment]
@StirStudios Apparently there is a heap limit when using the Github Actions VMs. I assume Node by default uses a _percentage_ of your system memory. Which, for the Github actions, the max memory that they have is 7 GB. 

My Node process is configured -- when running `v8.getHeapStatistics()` has `heap_size_limit: 4345298944`. - ~4GB. I assume the action is using ~2GB based on percentage. So, the solution was to up the limit to a more acceptable amount. Complicated process for certain.

**Comment by VividLemon** [comment]
@StirStudios As a side note, I do like the look of the code examples and some of the other changes you have made as well. As I'm sure you have noticed, the copy code button
image
is pure CSS. The recommended way to change this button is through CSS only. If you would like, you could try to play around with it to make it look nice, as a copy button.

Overall, thank you for the work here. I think it definitely makes it look nicer.

**Comment by StirStudios** [comment]
Great news, I think things look loads better as well. Always good to hear positive feedback. Totally agree with the copy option. I need to see what icons are being used and switch it.

Once I get my fork all set I will tackle this next.

**Comment by StirStudios** [comment]
Solved and added a new PR.

**Comment by VividLemon** [comment]
> Great news, I think things look loads better as well. Always good to hear positive feedback. Totally agree with the copy option. I need to see what icons are being used and switch it.
> 
> Once I get my fork all set I will tackle this next.

It might be a good idea to go back and do a refactor and make the example wrappers in their own components. Figure it would save a bit of time in the future. 
```html
<template>
  <b-card>
    <b-card-body>
      // real code
      <slot />
    </b-card-body>
    // etc etc
    HTML
    <slot name="html" />
  </b-card>
</template>
```

**Comment by StirStudios** [comment]
Ah great idea. I have begun the refactoring. Will let you know once it is done.

**Pull request merged**
