### PR TITLE
fix(BPopover and Btooltip): Fixes bootstrap-vue-next#1232 - do not create a new app fro each tooltip or popover

### LINKED ISSUE #1232: One vue App for each tooltip
I just noticed that vue App is created for each tooltip/popover on the page. Is it right?

### PR DESCRIPTION
**Pull request by james-muriithi**
# Describe the PR
The PR fixes #1232 (One App for each tooltip), by eliminating the need to create a new app for each tooltip or popover. I used the `render` function from Vue to achieve this. One issue I experienced with this method was it did not update when props changed. 

To get around this I had to remove the old rendered component, then re-render it on update

## Small replication
check #1232 

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

PS: this is my first open-source contribution, please be easy on me :))

### CODE REVIEW

**Review by VividLemon — COMMENTED** [review]
Looking good so far

**Comment by xvaara** [comment]
If I read this correctly we loose reactivity. This is no different from the old way of writing html with div.innerHTML = '...'. All the elements in tooltips are re-rendered on each update. 

If creating an app for tooltip is a problem, user should use components. 

I'm against this change. How we do thing now is the same way https://github.com/Akryum/floating-vue/blob/main/packages/floating-vue/src/directives/v-tooltip.ts does directives that stay reactive.

**Comment by xvaara** [comment]
This breaks so little and the things are weird anyway in directives so it might be ok for me.

I pushed a cleanup of unneeded $__state and $__app and imports. We just pass the props to the bind function.

**Review by xvaara — APPROVED** [review]

**Comment by james-muriithi** [comment]
> This breaks so little and the things are weird anyway in directives so it might be ok for me.
> 
> I pushed a cleanup of unneeded $__state and $__app and imports. We just pass the props to the bind function.

Thank you for this

**Comment by xvaara** [comment]
@james-muriithi you probably should be using tooltip as a component.

**Comment by VividLemon** [comment]
Regardless, i agree with the overall change of not polluting the workspace.

**Pull request merged**
