### PR TITLE
fix(docs ui): resolve broken theme and icons by properly importing the default theme

### PR DESCRIPTION
**Pull request by mhn147**
# Describe the PR

This PR fixes issues with icons in the docs (e.g., navbar search icon and others) and ensures that theme colors are applied correctly by properly importing the default vitepress theme.

To resolve these issues, I followed the recommended approach from the vitepress documentation: https://vitepress.dev/guide/extending-default-theme#using-different-fonts

Note: If this PR doesn't follow the conventional commit standards, please let me know, and I'll make the necessary adjustments.

## Small replication

1. navigate to https://bootstrap-vue-next.github.io/bootstrap-vue-next/
2. actual: search icon in the navbar search box not showing; icons in the search panel not showing
3. expected: icons to show properly

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [x] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

### CODE REVIEW

**Comment by VividLemon** [comment]
A commit that affects docs usually is just `docs: ...`, but this is not official "standard", it's more angular convention

> types other than fix: and feat: are allowed, for example [@commitlint/config-conventional](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional) (based on the [Angular convention](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#-commit-message-guidelines)) recommends build:, chore:, ci:, docs:, style:, refactor:, perf:, test:, and others.

But don't worry about it, I always squash/merge and adjust the commit messages

**Review by dwgray — COMMENTED** [review]
Thanks, @mhn147! Appreciate you finding a solution for this - I've been knocking off styling things in small pieces, this may fix a bunch in one go.

In my relatively limited understanding of VitePress, what you're proposing here is to move from a custom theme (that happens to pull in a bunch of styling from the default theme) to using the default theme with customizations. That is a good idea but may have unexpected consequences.

Could you please make sure that the doc site still builds and verify that the built (rather than the dev) version of the site renders as expected? That's the thing that has tripped me up the most. The way I've done that is to run `pnpm build` followed by `pnpm preview` from the `/app/docs` directory.

If that works, I'm all for shifting to this way of handling our docs.

**Comment by VividLemon** [comment]
> extends: DefaultTheme,

It also mentions this, not spreading. Don't know if it matters

**Comment by mhn147** [comment]
Thank you for your feedback!

I have limited knowledge of vitepress, but I was excited about this project and noticed the broken icons while reading the docs. 

>  what you're proposing here is to move from a custom theme (that happens to pull in a bunch of styling from the default theme) to using the default theme with customizations.

The icons were broken because we missed importing "vitepress/dist/client/theme-default/styles/icons.css". Initially, I thought of just adding the import, but I realized the default theme already includes the necessary CSS, so I opted to import the default theme instead of individual files. Hope this answers your question.

This approach is supported by the VitePress docs and is used in the Pinia docs site, so I followed it.<br/><br/>
                      
> That is a good idea but may have unexpected consequences.

I'm not deeply familiar with vitepress. While I didn’t see any issues when testing, I defer to your judgment regarding any potential unexpected consequences.<br/><br/>

> Could you please make sure that the doc site still builds and verify that the built (rather than the dev) version of the site renders as expected

Builds. I don't see any issues with preview. <br/><br/>

>
> > extends: DefaultTheme,
>
> It also mentions this, not spreading. Don't know if it matters

It seems like ```extends``` will pull in and call the parent theme ```enhanceApp```. I don't see a difference, but I'll use it.

**Comment by VividLemon** [comment]
I imagine using .extend would chain together function calls, instead of overwriting them. Maybe deep merge some nested object options idrk. Doubt it matters much

**Review by dwgray — APPROVED** [review]
LGTM

**Review by dwgray — APPROVED** [review]
LGTM

**Review by VividLemon — APPROVED** [review]

**Pull request merged**
