### PR TITLE
BDropdown: cleanup items

### LINKED ISSUE #1616: BDropdownItem variant default to secondary
property ```variant``` is BDropdownItem is set to 'secondary' by default 

Is it a mistake or wanted?

### PR DESCRIPTION
**Pull request by xvaara**
remove custom padding, margins and align with bootstrap
bind $attrs to inner element
set item variant default to null

closes #1616 

# Describe the PR

A clear and concise description of what the pull request does.

## Small replication

A small replication or video walkthrough can help demonstrate the changes made. This is optional, but can help observe the intended changes. A mentioned issue that contains a replication also works.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [ ] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

### CODE REVIEW

**Comment by VividLemon** [comment]
I take it the attrs inheritance is the same as bootstrap vue?

**Comment by xvaara** [comment]
> I take it the attrs inheritance is the same as bootstrap vue?

Yes

**Review by VividLemon — APPROVED** [review]
Looks good, thanks

**Comment by helenezspeer** [comment]
I don't think this fix is included in the 0.15.5 release of the same day, as I'm still seeing the px/py classes in the dropdown form component.

**Pull request merged**
