### PR TITLE
fix(modalControllerPlugin): modal created by show and confirm now can…

### PR DESCRIPTION
**Pull request by Pequem**
… be closed (#1921)

# Describe the PR

Fix modalControllerPlugin to allow modals to be closed

## Small replication

Can use doc example of useModalController

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

### CODE REVIEW

**Comment by Pequem** [comment]
I tried to create a unit test, but in the test I was unable to make the modal disappear, however, testing manually the modal is disappearing normally.

**Comment by VividLemon** [comment]
How does changing it to a ref fix the issue?

**Comment by VividLemon** [comment]
Oh yeah, i remember why theyre computeds. Its because you can dynamically supply reactive props as inputs. I think this commit may have broken that

**Comment by Pequem** [comment]
Could you give me an example ? 

I will test with writable computed

**Comment by Pequem** [comment]
I don’t know why, but the version 0.16.6 works with computed

**Comment by Pequem** [comment]
I created another PR with the new solution propose to make the commits clean.
https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1924

**Pull request closed without merging**
