### PR TITLE
BModal documentation for shown event has incorrect timing

### PR DESCRIPTION
**Pull request by anrolmar**
# Describe the PR

Change the description for the shown event.

## Small replication

https://stackblitz.com/edit/github-vf39ah?file=src%2FApp.vue

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [x] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

### CODE REVIEW

**Comment by VividLemon** [comment]
The shown, show, hide and hidden could all be updated.

In addition to that, there are multiple components that define all four of those events. So, you could make a more generic definition, you could reuse the definitions for all components with those events

**Comment by anrolmar** [comment]
> The shown, show, hide and hidden could all be updated.

I'll do that.

> In addition to that, there are multiple components that define all four of those events. So, you could make a more generic definition, you could reuse the definitions for all components with those events

I think this should be another issue

**Comment by xvaara** [comment]
@VividLemon I'm a little confused. Isn't show emited before because it's cancelable? shown is emited after? at least that's how it works on the other components...

**Comment by VividLemon** [comment]
> @VividLemon I'm a little confused. Isn't show emited before because it's cancelable? shown is emited after? at least that's how it works on the other components...

Yes, this PR has changed the wrong description

**Pull request closed without merging**
