### PR TITLE
Small theming update for purple navbar

### PR DESCRIPTION
**Pull request by StirStudios**
Very small update to include a purple navbar like BS with some extra vars and commenting.

### CODE REVIEW

**Comment by VividLemon** [comment]
I'm not opposed to using a different color

**Comment by StirStudios** [comment]
@VividLemon what about this type of thing?

SCR-20230603-piqo

**Comment by VividLemon** [comment]
> @VividLemon what about this type of thing?
> 
> SCR-20230603-piqo

I've never been a huge fan of large gradient changes. I've always found it to be a bit gimmicky. I'm not opposed to a slight gradient, if you'd like to lower the percentage.

**Comment by StirStudios** [comment]
Absolutely agree, as it is a gimmic! So can we get away from both of these colors? Does it matter?

Some Options:

Option 1
SCR-20230604-mzea

Option 2 (total mistake but thought it was cool in some way)
SCR-20230604-mzzk

Option 3
SCR-20230604-naoc

Option 4
SCR-20230604-nbop

Option 5
SCR-20230604-ncns

Option 6
SCR-20230604-ndch

Option 7
SCR-20230604-ndyb

Option 8
SCR-20230604-ndyb

Option 9
SCR-20230604-ngcr

I think a subtle gradient adds a little flavour. That is me, thoughts?

**Comment by VividLemon** [comment]
I think the first one look nice

**Comment by StirStudios** [comment]
Done!

**Pull request merged**
