### PR TITLE
docs(BAvatar): parity pass

### PR DESCRIPTION
**Pull request by dwgray**
# Describe the PR

- Fix doc bugs.
- Fill out the component reference
- Write migration guide
- Update the parity report

I have not updated the `BLink` related properties for two reasons
1. I think it's better to document BLink, and then we can backfill its usage here
2. I'm not entirely clear where we landed  #1913 @VividLemon - did you land on just keeping things as they are? If so, what happens with properties like `variant` that are relevant to both `BLink` and `BAvatar`?

## Small replication

N/A

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [x] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

### CODE REVIEW

**Comment by dwgray** [comment]
@VividLemon Do you know off the top of your head if router links are supported by BAvatar? In taking a quick look at BLink it seems like they should be. If that's the case I'll put this PR into draft mode and tackle BLink & https://bootstrap-vue.org/docs/reference/router-links next. Any thoughts/references you have beyond the code on what BSVN supports for router-links would be really helpful.  Thanks!

**Comment by VividLemon** [comment]
> Do you know off the top of your head if router links are supported by BAvatar?

BAvatar uses BLink which can use RouterLink

**Comment by VividLemon** [comment]
> m not entirely clear where we landed https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1913 @VividLemon - did you land on just keeping things as they are? If so, what happens with properties like variant that are relevant to both BLink and BAvatar?

It kind of seems like too much. Idrk. Maybe it could be a good addition idrk.

**Comment by dwgray** [comment]
> > Do you know off the top of your head if router links are supported by BAvatar?
> 
> BAvatar uses BLink which can use RouterLink

Thanks, I cleaned up the docs to reflect this and refactored, so that BAvatar uses the BLink property reference as an extension. I think that makes this good to go. I'll document the BLink soon, but I don't think having those props empty should block this PR.

**Comment by dwgray** [comment]
> > m not entirely clear where we landed #1913 @VividLemon - did you land on just keeping things as they are? If so, what happens with properties like variant that are relevant to both BLink and BAvatar?
> 
> It kind of seems like too much. Idrk. Maybe it could be a good addition, I'm not sure

Yeah, I agree that it's a stretch. And with the ability to document extensions, I think this works reasonably well in general. In this particular case, the `variant` prop on `BAvatar` hides the `variant` prop on `BLink`, so for a text avatar with a link, the link is unreadable (take a look at the example in the docs). This is a pretty corner case, I've opened #2102 to address it in the future.

**Review by VividLemon — APPROVED** [review]

**Pull request merged**
