### PR TITLE
fix(docs): build infinite loop

### LINKED ISSUE #1702: Docs build infinite loop
### Describe the bug

There exists some issue with processing the docs. First, during build it executes an infinite loop. The second issue is that when "dev" navigation of pages declares "vitepress data not properly injected in app". I suspect these two things are related. I'm not sure when this started (though its from a series of my changes). Something in https://github.com/bootstrap-vue-next/bootstrap-vue-next/commit/ca16a168687dc0e17d6dc5c6210205c1911dd793

### Reproduction

f

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sidneygijzen**
# Describe the PR

Wrapping the `setInterval` in the SFC setup in a `inBrowser` check solves the infinite loop, see [this comment](https://github.com/vuejs/vitepress/issues/562#issuecomment-1106061640) in the vitepress issue queue. I was able to build the docs successfully locally without an infinite loop. 

Fixes #1702.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

### CODE REVIEW

**Review by VividLemon — CHANGES_REQUESTED** [review]
Let's instead put the interval functions into onMounted hooks. Perhaps you can use useIntervalFn from vueuse, I'm not sure if they automatically run onMounted or not... If not, then you can create a composable, something like "useSafeIntervalFn" instead

**Comment by sidneygijzen** [comment]
Thanks for the quick review. I will have a look.

**Comment by sidneygijzen** [comment]
@VividLemon I think you only need one of the two options you described:

instead of
```
if (inBrowser) {
  setInterval(() => {
    firstRef.value.body = `${Math.random()}`
  }, 1000)
}
```

Both the `onMounted` variant
```
onMounted(() => {
  setInterval(() => {
    firstRef.value.body = `${Math.random()}`
  }, 1000)
})
```

or  the vueuse `useIntervalFn` works: 
```
useIntervalFn(() => {
  firstRef.value.body = `${Math.random()}`
}, 1000)
```
`useIntervalFn` [has a built-in check for `isClient`](https://github.com/vueuse/vueuse/blob/main/packages/shared/useIntervalFn/index.ts#L62), so an onMounted hook is not needed.

In both cases the docs build successfully. Which version do you prefer?

**Comment by VividLemon** [comment]
> @VividLemon I think you only need one of the two options you described:
> 
> instead of
> 
> ```
> if (inBrowser) {
>   setInterval(() => {
>     firstRef.value.body = `${Math.random()}`
>   }, 1000)
> }
> ```
> 
> Both the `onMounted` variant
> 
> ```
> onMounted(() => {
>   setInterval(() => {
>     firstRef.value.body = `${Math.random()}`
>   }, 1000)
> })
> ```
> 
> or the vueuse `useIntervalFn` works:
> 
> ```
> useIntervalFn(() => {
>   firstRef.value.body = `${Math.random()}`
> }, 1000)
> ```
> 
> `useIntervalFn` [has a built-in check for `isClient`](https://github.com/vueuse/vueuse/blob/main/packages/shared/useIntervalFn/index.ts#L62), so an onMounted hook is not needed.
> 
> In both cases the docs build successfully. Which version do you prefer?

Just onMounted is fine

**Comment by sidneygijzen** [comment]
Thanks. Changed it to onMounted.

**Pull request merged**
