### PR TITLE
fix[BDropdown]: toggle show class for dropdown list

### PR DESCRIPTION
**Pull request by mdzoon**
# Describe the PR

A clear and concise description of what the pull request does.

## Small replication

A small replication or video walkthrough can help demonstrate the changes made. This is optional, but can help observe the intended changes. A mentioned issue that contains a replication also works.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

### CODE REVIEW

**Review by mdzoon — COMMENTED** [review]
Yep. The syntax makes more sense `:class="[menuClass, {show: modelValueBoolean}]"`
I would also adjust line 28 accordingly :class="[toggleClass, {show: modelValueBoolean}]" - toggle 'show' for button elm.

**Review by VividLemon — APPROVED** [review]

**Comment by VividLemon** [comment]
Code aside, what exactly does this PR do?

**Comment by mdzoon** [comment]
Hello!

Some background:

I am migrating my projects from Nuxt2 to Nuxt3. It forces me to replace
bootstrap-vue with bootstrap-vue-next.
I have spotted that some elements work differently/do not work at all after
the swap.
HTML and CSS adjustments fixed most of the issues. However, there are two
notable exceptions - navbar dropdown and collapse.

I compared the dropdown in bootstrap-vue, bootstrap5 and bootstrap-vue-next
and picked up a few discrepancies:

1. The 'show' class should toggle for ul.dropdown-menu - seems to be a
logical choice which follows Bootstrap5 pattern
2. The transform property for ul.dropdown-menu has a 'weird' initial value,
for example:
{
  position: absolute;
  left: 0px;
  top: 0px;
  transform: translate(898px, 72px);
  max-height: 896px;
  max-width: 510.933px;
  display: none;
}
while it should be:

transform: translate(0px, 46px);  - left corner and button's height

if we want to display it flush left, under the button.

My fix addresses the point 1.

I struggle to find a source of the initial values for the transform
property  ( i.e. transform: translate(898px, 72px); ) in point 2.
I believe, it comes from line 164 const floating = ref<HTMLElement | null>(
null) in packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue
However, I do not understand why the values change after the element is
open. Again Bootstrap5 element retains the same correct value.

I hope it clarifies.


I also have an issue with the collapse - v-b-toggle directive. But it is a
different topic.

I am happy to contribute to the project, but I will need some 'parental
guidelines' ;)

Regards

Michael

**Comment by xvaara** [comment]
> 2. The transform property for ul.dropdown-menu has a 'weird' initial value, for example: { position: absolute; left: 0px; top: 0px; transform: translate(898px, 72px); max-height: 896px; max-width: 510.933px; display: none; } while it should be: transform: translate(0px, 46px); - left corner and button's height if we want to display it flush left, under the button. My fix addresses the point 1. I struggle to find a source of the initial values for the transform property ( i.e. transform: translate(898px, 72px); ) in point 2. I believe, it comes from line 164 const floating = ref<HTMLElement | null>( null) in packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue However, I do not understand why the values change after the element is open. Again Bootstrap5 element retains the same correct value. I hope it clarifies.

Is the dropdown not working for you? We use a more modern positioning library than bootstrap or bootstrap-vue.
Open an issue if it's not working for you.

**Pull request merged**
