### PR TITLE
fix(BFormGroup): fix missing margin bottom

### PR DESCRIPTION
**Pull request by loicduong**
# Describe the PR

fix https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/2316

## Small replication

A small replication or video walkthrough can help demonstrate the changes made. This is optional, but can help observe the intended changes. A mentioned issue that contains a replication also works.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

### CODE REVIEW

**Comment by xvaara** [comment]
I really dislike that we add classes and margins etc. to components. If the user wants a margin, they can add mb-3 to the components class. Do we need this by default?

@VividLemon should we define our guidelines about these things somewhere? I could write a little proposal and you could take a look at it... Or are we aiming at maximum compatibility with BV2?

**Comment by loicduong** [comment]
@xvaara I think we can set up a default value, if we need to change it we can use class to override

**Comment by VividLemon** [comment]
> I really dislike that we add classes and margins etc. to components. If the user wants a margin, they can add mb-3 to the components class. Do we need this by default?

I have no opinions. @xvaara You can manage this issue. If you want to remove it, put it in the migration guide

**Comment by dwgray** [comment]
I'm with @xvaara on this one, I don't think we should be adding/maintaining extra CSS explicitly for BSV/boostrap4 compatibility _especially_ when it's related to something that BS5 has explicitly changed.

The way my head was going with this is that we could have a suggested configuration to pick up some of these things for folks that are looking for a smooth path migration from BSV - at minimum document in migration, but if there are more than one or two of these, we could just have a configuration that for people to grab. Note that I am not suggesting that we maintain a compatibility switch, just documentation.

I thought there was a smooth path to this - we basically just want to add the default class of "mb-1" to `BFormGroup`.
e.g. 

```ts
createApp(App)
  .use(createBootstrap({components: {BFormGroup: {class: 'mb-1'}}}))
  .use(router)
  .mount('#app')
```
But since the class attribute is a fall-through attribute this doesn't work because (1) typescript doesn't know about it and (2) the class from the default doesn't get merged. But if I explicitly set `class="mb-1"` on a `BFormGroup` the class gets merged correctly.

Is there a different way to do this? I think it would be generally useful to be able to set `class` defaults for components and we can for more complex components that have wrapper classes, etc. but not in this case. Unless I'm missing something?

**Comment by xvaara** [comment]
@dwgray We don't want to add the class as a props, that causes so much headache. Maybe add wrapperClass to that component also? Or add it to everyclass? We could have extraAttrs for each component, bind it to the root (not clear on every component) then we could have more customising the html. But I'm not a fan of those. Just add the mb-3 to the component. Like bootstrap5 docs show input groups: `<div class="input-group mb-3">`.

Or this should at least have a class so that people can but the margin in their own style.css? Or let's say every our own custom component should have a unique class. That might be easiest way for this.

**Comment by loicduong** [comment]
@xvaara What will our decision be? I also like the solution like Bootstrap 5, showing it in examples and adding it to the migration section.

**Comment by dwgray** [comment]
> Or this should at least have a class so that people can but the margin in their own style.css? Or let's say every our own custom component should have a unique class. That might be easiest way for this.

I'd be good with any of the options @xvaara suggested, but I like having a unique class per component - that gives a great deal of flexibility without being opinionated. That combined with information in the migration guide should make it readily consumable by someone migrating from BSV.

**Comment by xvaara** [comment]
I'm in favour of just adding the class for the components. if bootstrap is in basic form (ie modal) should we also be? Like class="form-group" ? do we need the bv-prefix?

**Comment by VividLemon** [comment]
> do we need the bv-prefix?

All custom classes should have this prefix. Not necessarily by requirement, but to eliminate conflicts, it shows where the class came from, & is a convention started by bv

**Comment by xvaara** [comment]
closing in favor of #2344

**Pull request closed without merging**
